version: '3.8'

# Defining the named volume
volumes:
    database:

services:

    database:
        image: 'postgres:latest'
        restart: 'always'
        environment:
            POSTGRES_USER: 'admin'
            POSTGRES_PASSWORD: 'admin'
            POSTGRES_DB: 'ftests_inventory'
        volumes:
            # Mounting the named volume
            - 'database:/var/lib/postgresql/data/'
        ports:
            - '5432:5432'