GET http://localhost:8072/api/tests/all
Accept: application/json

###
GET http://localhost:8072/api/tests/allInvs
Accept: application/json

###
GET http://localhost:8072/api/tests/find?team=Accounts
Accept: application/json

###
GET http://localhost:8072/api/tests/find?team=Accounts&pageSize=10&pageIndex=1
Accept: application/json

###

PUT http://localhost:8072/api/tests/put
Accept: application/json
Content-Type: application/json

{
  "SimpleValue": "Value of string",
  "kind": "Test"
}
###

PUT http://localhost:8072/api/tests/putInventory
Accept: application/json
Content-Type: application/json

{
  "SimpleValue": "Value of string",
  "kind": "Inventory3"
}
###
